#!/usr/bin/python
# encoding: utf-8

PID_FILE = '/var/run/catchrobot.pid'

I2C_ADDRESS = {
    'MOTOR1': 0x10,
    'SERVO1': 0x20,
    'SERVO2': 0x21,
}

JOYSTICK_NUMBER = 0

PAD_BUTTON = {
    'LINE_HAND_OC': 4,
    'SUICIDE_HAND_OC': 5,
    'INITIALIZE': 11,
    'RETRY': 10
}

PAD_HAT = {
    'AIR_CYLINDER_TURN': 0,
    'AIR_CYLINDER_OC': 1,
}

PAD_AXIS = {
    'LINE_ARM_BACK_FORTH': 0,
    'LINE_ARM_UP_DOWN': 3
}

AIR_CYLINDER_MODULE_ANGLE_UNIT = 20
AIR_CYLINDER_OPEN_ANGLE = 160
AIR_CYLINDER_CLOSE_ANGLE = 35
SUICIDE_HAND_OPEN_ANGLE = 160
SUICIDE_HAND_CLOSE_ANGLE = 35
SUICIDE_ARM_EXPAND_ANGLE = 160
SUICIDE_ARM_RETURN_ANGLE = 30
LINE_HAND_OPEN_ANGLE = 160
LINE_HAND_CLOSE_ANGLE = 30
JOYSTICK_BACKLASH = 0.2